### ISSUE TITLE
Method chaining on uncorner

### ISSUE THREAD

**Issue by antonycarthy** [malsup/corner#1]
The following code didn't do what I expected (remove the current corner and recorner the selected elements):
$(".selector").uncorner().corner();
This would be a common task for recornering elements for example.

Replacing line 173 with:
$.fn.uncorner = function() {$('.jquery-corner', this).remove();  return this; };
Solved the problem. Perhaps remove() doest return jQuery? 
I don't know enough about jQuery to know whose bug this is, but the line above fixes it.

**Comment by malsup** [comment]
Fixed in v1.96.  Thanks for catching this, Antony.
