### ISSUE TITLE
HTML Text Input Elements not Cornered

### ISSUE THREAD

**Issue by noelweichbrodt** [malsup/corner#11]
The following renders a rounded div but not a rounded input element in FF3, IE7,
IE8, and in fact causes the input box border to disappear completely:

http://www.weichbrodt.org/jquery.corner.test.html

Doubly frustrating because border-radius _does_ round the corners of input elements in FF3.

Cheers!

**Comment by noelweichbrodt** [comment]
the plugin does not support <input> elements :(

**Comment by malsup** [comment]
Correct.  The plugin is meant to apply its effect to block level elements.
