### ISSUE TITLE
"keep" attribute broken in all versions of IE

### ISSUE THREAD

**Issue by nspitko** [malsup/corner#13]
the "keep" attribute allows for rounded corners with a border on IE/Chrome (tested), but IE's behavior is to simply render the original non-rounded border instead.

This happens in both my tests and on the demo site at malsup.com

**Comment by PHLAK** [comment]
I have noticed the same thing and would like to see this fixed as well.

**Comment by steelhead** [comment]
The "keep" attribute does keep the border around the DIV object but it sits on top of the rounded corner. Basically you have two types of corners at the same time shown - the one created by the object's border and the round one created by jquery. This happens in IE8, but it also happens in Firefox if you remove support for native rounding from the code (-moz-border-radius).
Thank you.

**Comment by malsup** [comment]
The "keep" option was added only for exposing interesting effects.  It is not meant to support rounded borders in IE.  For that you either need to use nested divs (as in the Adornment demos) or wait for IE9.  Sorry.

**Comment by Tricks** [comment]
I used the nested divs and basically it worked OK. However, when chosing a small border of 1px, in IE the top corners show filled straight corners outside the rounded border. I took a section of your demo-page to show this effect. See: http://www.tricksweb.nl/corners.html
