### ISSUE TITLE
Image background break corners on Firefox

### ISSUE THREAD

**Issue by fidoboy** [malsup/corner#14]
I've noticed that if i use a background picture the corners are not rounded when using Firefox; all other browsers are working fine (Safari, Internet explorer, Opera, Chrome...). How can i solve this?

thanks in advance,

**Comment by djmccormick** [comment]
I'm also having this issue.

**Comment by malsup** [comment]
Can you post a link?

**Comment by malsup** [comment]
Seems to work for me:  http://www.malsup.com/jquery/corner/image2.html
