### ISSUE TITLE
Meta data-corner won't work if a setting is provided in corner()

### ISSUE THREAD

**Issue by gravis** [malsup/corner#15]
Hi,
If I want to set a default rounding of 5px + use the meta data-corner, the data-corner is ignored :

```
$('.rounded').corner("5px");

<div class="rounded" data-corner="bottom">My bottom rounded div</div>
```

The div will be rounded using 5px on each corner, the "bottom" setting is ignored. 
Therefore, the only way to do what I want is currently to add the 5px in every rounded block of the page (a lot !).

Thanks :)

**Comment by malsup** [comment]
This is now supported.
