### ISSUE TITLE
jQuery Corner & Safari 4.0.4

### ISSUE THREAD

**Issue by Senne** [malsup/corner#16]
The plugin doesn't work properly with Safari 4.0.4. It displays the corners, but they are not as smooth as before, links aren't clickable anymore and inline elements can't be rounded. It also generates lots of divs which makes the code messy.

**Comment by osxman** [comment]
To make the change work also in Panic CODA's intergrated webkit the line could be:
var webkit = $.browser.safari && /AppleWebKit\/[5-9]/.test(ua);

Kind Regards Frank, Amsterdam.

**Comment by malsup** [comment]
I believe this is fixed in v2.02 of the plugin.
