### ISSUE TITLE
ie memory leak

### ISSUE THREAD

**Issue by timbell** [malsup/corner#17]
Hi - just wanted to report a memory leak using Internet Explorer + the corner plugin. Memory is lost on each page refresh (observed using ie6). It can be fixed as follows (call to removeExpression added):

```
var expr = $.browser.msie && (function() {
    var div = document.createElement('div');    
    try { div.style.setExpression('width','0+0'); div.style.removeExpression('width'); }    
    catch(e) { return false; }    
    return true;
})();
```

Cheers,

Tim

**Comment by malsup** [comment]
Thanks for this fix.
