### ISSUE TITLE
Border does not display: IE8 with jQuery 1.3.2

### ISSUE THREAD

**Issue by ghost** [malsup/corner#18]
Is there an issue with the corner plugin with jQuery 1.3.2?  This is the first time this has happened, and I've used your plugin for a long time.  When viewing in IE8, the element does not have a border.  When reloading the page with javascript turned off, the border is there.

**Comment by reformatco** [comment]
I have also had the same problem, have you had any idea for a fix?

**Comment by lcaos** [comment]
Same problem with IE8 with or without compat on, jquery 1.4.2

**Comment by malsup** [comment]
That's not new, that's how the plugin works.  You can use the 'keep' option to keep the border, but in IE it will not be round (or any other shape but square).

**Comment by reformatco** [comment]
Thanks mal, with respect why use the plugin then and not simply define the style as being rounded with CSS3?

**Comment by malsup** [comment]
There are limitations, but it works just fine in IE if you don't need borders.

**Comment by reformatco** [comment]
Yes I see, doh i forgot you might need to round corners without borders oops

**Comment by ghost** [comment]
If you want rounded borders in ie 7-8 you can wrap the dom element in another one with that your border-color as background-color and give it 1px padding. I think i saw this in a example from jquery.corner.

$(".myElement").wrap('div class="border-helper"'); //add the <> :)
$(".myElement, .border-helper").corner("5px");
//
Also some css proprieties(margin, padding, position) will have to be transfered to the container and border-color transfered as background color to the container.

In my project, i stopped using borders and did the adaptation above wherever i needed it (i mean, did not do things separately for ie respectively good browsers)
