### ISSUE TITLE
Corners not rounding in Google Chrome 2

### ISSUE THREAD

**Issue by winwillme** [malsup/corner#2]
When i use the corner method on the window.open event in Chrome no corners are rounded. jQuery v1.3.2

**Comment by malsup** [comment]
The corner plugin works fine in Chrome as can be seen on the demo page:

http://www.malsup.com/jquery/corner/

Can you post a link to the page you're having problems with?

**Comment by malsup** [comment]
Just fixed an issue in Chrome that may have caused a problem.  If you get a chance to test it please let me know if it works.
