### ISSUE TITLE
Border "keep" not worked in IE6

### ISSUE THREAD

**Issue by ibnu82** [malsup/corner#23]
i try this plugin..work well in FF, but the border "keep" doesn't work in IE6. Please advice how to make it work in IE6. anyway, this is a very good plugins. thanks

**Comment by malsup** [comment]
Use the adornment pattern shown on the demo page.  IE doesn't not support rounded borders.

**Comment by ibnu82** [comment]
i had used addorment pattern,,using inner div and outer div. it's running well in firefox, but in IE6,,there is no corner in top-right.
