### ISSUE TITLE
How to using "the Corner Plugin with Images" via ajax

### ISSUE THREAD

**Issue by ibnu82** [malsup/corner#24]
when i used "the Corner Plugin with Images" from the page it self, it running well.
but, when i tried to call the image via ajax:
$.fn.corner.defaults.useNative = false;
$(document).ready(function(){
        $("#imgBox").corner("15px");
    });

the image still doesn't have rounded corners.
can yu give me an example how to call corner plugin with image via ajax..
thanks..

**Comment by malsup** [comment]
Can you post a link to your test page?

**Comment by ibnu82** [comment]
this is my test page link:
http://monique-salon.com/testpage/index.html
http://monique-salon.com/testpage/update.html
the first image in index.html, rounded perfectly.
but when i click update button, i used imgBox from update.html:
but the image doesn't rounded.

thanks..

**Comment by malsup** [comment]
Change the markup returned by update.html to use a different ID for the div:
    <li>
        <div id="imgBox2"><img src="beach1.jpg" /></div>
    </li>
Then invoke corner again in your success callback:
    success: function(html){
        $("ul#update").prepend(html);
        $('#imgBox2').corner('15px');
        $("ul#update li:first").slideDown("slow");
    }

**Comment by ibnu82** [comment]
it works..
thanks a lot malsup.. you are great..^_^
