### ISSUE TITLE
Incorrect height in IE with min-height hack

### ISSUE THREAD

**Issue by peterpoe** [malsup/corner#27]
When rounding corner on a container using the min-height hack (http://www.dustindiaz.com/min-height-fast-hack/), the bottom corners are rendered at the 'auto' height, resulting in bad display.
Solved this changing line 144 from this:
    var cssHeight = $.curCSS(this, 'height');
to this:
    var cssHeight = $(this).outerHeight()+'px';

**Comment by malsup** [comment]
Thanks!
