### ISSUE TITLE
Transparent corners

### ISSUE THREAD

**Issue by kanteldata** [malsup/corner#29]
the only effect that will yield transparent corners is "round".  Is it possible to have transparent "beveled" corners?

thanks

**Comment by malsup** [comment]
No, not with the current implementation.

**Comment by kanteldata** [comment]
Thank you. I noticed that in IE8, the "corners" are showing white but are fine in Firefox and Safari.  Is there something I am missing?

**Comment by malsup** [comment]
Post a link please.

**Comment by kanteldata** [comment]
https://scmgportal.dticloud.com/csp/cms/sites/SunNews/PuntaGorda/index.csp?CSPCHD=00000001000029ndNy9600000096_d1yWAA3kccG3Lahvxww--

**Comment by malsup** [comment]
Right, this is because the plugin does NOT support transparency in IE and so it does not work well over background images.  Please read the note at the top of this page to understand more:
http://www.malsup.com/jquery/corner/

**Comment by kanteldata** [comment]
Thanks.
