### ISSUE TITLE
Rounded Corners with Wordpress

### ISSUE THREAD

**Issue by kirillzubovsky** [malsup/corner#3]
Hi Dave and Mike,

I am trying to use rounded corners with a Wordpress theme and I just can't figure out what's not working.

jQuery comes with wordpress now and the only thing that I need to adjust, when using the actual library, is to change $ sign to 'jQuery'.

However, when I do the same to your plug-in and call it from the page, it doesn't seem to work.

Any ideas where I am going wrong or what information could help you help me?

Thank you very much!

**Comment by malsup** [comment]
You do not need to change the $ in the corner plugin.  The plugin is written using a closure that provides safe access to the $ within the plugin.
