### ISSUE TITLE
Corner over bg image in IE.

### ISSUE THREAD

**Issue by kmiles** [malsup/corner#30]
First off, great script.  I just found it, but it is making web development much faster and easier for me.

I noticed today that the corners over a page background image are working, but the corner backgrounds are of the page background color and not pulling in the background image.
http://www.tryoutresults.com/inside.php?pg=associations

I am going to poke around to see if I can fix it, but I was wondering if this is a known issue with an easy fix, or now.

**Comment by malsup** [comment]
It's not really an issue, just a limitation based on how the plugin is implemented.  For details, look at the note at the top of the demo page:
http://jquery.malsup.com/corner/

**Comment by kmiles** [comment]
Ah, that makes good sense.  Thanks for the quick response, sorry for missing that in the documentation.
