### ISSUE TITLE
can not use corner with duplicate #id

### ISSUE THREAD

**Issue by absolutex** [malsup/corner#32]
,my code 

$("#member-box").corner("top 8px");

<_div id="member-box-main"_>
test
<_/ div_>

1 box is ok but if have a box more than 1

cornor is not show after first box :O

thanks.

**Comment by malsup** [comment]
There are a lot of things in JavaScript that you can't do with duplicate IDs because that is invalid markup.  By definition, IDs must be unique.  If you want jQuery to select multiple elements then you must provide a valid selector.  Some examples:

```
$('#myId1,#myId2').corner();
$('div.myClassname').corner();
```

**Comment by absolutex** [comment]
Thanks :D
