### ISSUE TITLE
Error in Internet Explorer 6 / 8

### ISSUE THREAD

**Issue by timini** [malsup/corner#34]
IE 8 is giving me the following error:

Line: 157
Error: Unexpected call to method or property access.

regards,
Tim

**Comment by malsup** [comment]
Please post a link to a sample page that shows the problem.  Thanks.

**Comment by constantm** [comment]
I've been getting it too: http://aquasolar.co.za/

**Comment by malsup** [comment]
This plugin cannot be used for cornering select or input controls, or any other inline element.  IE does not allow it.

**Comment by constantm** [comment]
Thanks so much. I figured that out after literally weeks of searching around what's going wrong as I didn't see it was problem caused by cornering the inputs. Thanks for a great plugin
