### ISSUE TITLE
Some problems with IE browsers

### ISSUE THREAD

**Issue by dev4press** [malsup/corner#36]
1. When I try to add corner to INPUT element, I get JavaScript error in corner.js file in line 163 where is:
   >bot ? this.appendChild(d) : this.insertBefore(d, this.firstChild);

saying that object doesn't support method.
1. Once the corner method is executed, elements affected loose borders, and corner is visible on the content, but the border is gone.

**Comment by parndt** [comment]
Input elements are not supported by this script (In IE browsers). To get around this I have a version which specifies elements = this; elements = elements.not('input') .. I'll see about updating my fork later.

**Comment by dev4press** [comment]
OK, and what about borders?

**Comment by parndt** [comment]
Oh yeah, I've noticed the same issue just yesterday with the borders. Meant to write that in my last reply :)  Do you have any idea what's going on?

**Comment by dev4press** [comment]
In my case I have DIV with dark border, some gray fill on white background. Once the round is executed, border disappears and element gets rounded, only fill part, no border.

**Comment by parndt** [comment]
Right, in my case I have a grey background with a darker grey border and the border disappears but the grey background gets rounded. Sounds like same issue!

**Comment by dev4press** [comment]
Exactly the same. But I also have one more strange issue. One element without a border, only green fill, it gets rounded, but when a cursor goes over it, element becomes transparent and it's no longer filled!

Same thing happens in IE6, IE7 and IE8.

**Comment by elmonty** [comment]
I'm having the same issue, but I don't have an INPUT element.  I wonder why this code:

bot ? this.appendChild(d) : this.insertBefore(d, this.firstChild);

is used instead of using jQuery.

In my case, I have a DIV that contains a TABLE.  I'm invoking corner() on the div.  Here's its CSS:

DIV.grayContainer
{
    padding: 15px;
    background-color:#b1b5b9;
}

**Comment by dev4press** [comment]
I must admit that I gave up on making rounded corners in IE6/7/8. It barely works and it works only is some cases, and it can't give results I am looking for. This is great plugin for other browsers that use CSS for rounding.
