### ISSUE TITLE
IE8 Issue 

### ISSUE THREAD

**Issue by gishdog** [malsup/corner#4]
In IE8 I receive the following error:

Line: 132
Error: Unexpected call to method or property access.

**Comment by gishdog** [comment]
Also - I am using corner v 1.97 and the url for the site is http://quickie.apylive.com

**Comment by malsup** [comment]
This error is occurring because you are trying to corner an <input> element.  The plugin does not support that since input elements can not have child elements.  That is a limitation of this implementation.

**Comment by yanickrochon** [comment]
An idea is to put the input element inside a corered div, than make the input element without border and of the same background color as the div

**Comment by malsup** [comment]
Yanickrohon has the right idea.  Yhat's how I'd solve handle corning inputs.

**Comment by sagi-zz** [comment]
Hi. I've made a small function that wraps inline elements with a div and corner it.
Here it is: http://pastebin.ca/1701600
If you plan to support inline elements I can help with merging this function to the plugin.
It works great, however there is one issue: event handlers of the inline elements that changes their css, won't change the wrapper css. so if you use event handlers in input, you should handle it manually (shouldn't be hard).
