### ISSUE TITLE
Rendering quirk in IE 7

### ISSUE THREAD

**Issue by swoxo** [malsup/corner#5]
Corner() works sensationally well for me in Chrome and FF, but in IE 7, the page renders first, then the corners are modified a split-second later, causing a distracting animation effect.  These are the first two lines of my code:
    $(document).ready(function(){
        $(".tab").corner("tl tr 10px");
Other jQuery code following the corner statement is behaving as expected, just the corners are doing this two-step rendering.
Has anyone else noticed this behavior, or is it unique to me?  Is there a work-around?

**Comment by reformatco** [comment]
I have had something similar but with me it opens up my page, borders appear for a split second then disappear (when corners render).

**Comment by jondkinney** [comment]
I am having this problem as well. IE7 only...

**Comment by reformatco** [comment]
I ended up using curvycorners.js and works fine, using the CSS selector means you just add the -moz-border-radius and -webkit-border-radius to the class and upon render curvycorners.js just replaces it with nice anti-aliased edges in IE.

**Comment by jondkinney** [comment]
I actually got this to work in IE7 by adding a conditional comment for IE7 only and setting a global style for "div" to display:inline-block like so...

<pre>
div{
  display:inline-block;
}

.clear{
  height:0px; /*to fix empty "clear" divs inheriting a height of the default font-size*/
}
</pre>
