### ISSUE TITLE
'Keep' borders don't fit curve of corners in IE

### ISSUE THREAD

**Issue by ozzyogkush** [malsup/corner#50]
Using IE7 and 8, trying to do a simple 'keep bottom 6px' or similar command on a div (either using .corner() or as data-corner in the div itself), the object will corner correctly but the border stays square. You can see this behavior at http://jquery.malsup.com/corner/ in the 'Pick Your Colors (or keep your borders)' section.

**Comment by malsup** [comment]
Yes, that's a limitation.  Sorry.

**Comment by ozzyogkush** [comment]
Any chance that'll be fixed in future versions?

**Comment by malsup** [comment]
Nope.
