### ISSUE TITLE
Broken with latest jQ

### ISSUE THREAD

**Issue by JohnMcLear** [malsup/corner#62]

**Comment by chrissutton** [comment]
I think what JohnMcLear is referring to is that .browser checks are going away in the jquery 1.9 release (unless you are using jquery.migrate). And in jquery 2.0 it will be gone completely.

**Comment by JohnMcLear** [comment]
yep sorry I should have said.

**Comment by chrissutton** [comment]
Thanks

**Comment by JohnMcLear** [comment]
Thanks
