### ISSUE TITLE
Corners on table not fully working

### ISSUE THREAD

**Issue by gravis** [malsup/corner#7]
Hi,

I have a small table where I want to set-up some corners. Unfortunately, it's only working on safari. Since borders are set on the table itself, I don't want to embed all of this in a div.
Anyone having the same issue ?

Thanks

**Comment by gravis** [comment]
update : It's now working in safari thanks to native corners. Anyway, IE won't round anything on a table.

**Comment by malsup** [comment]
Tables are tricky.  Your best bet is to wrap in a div and corner the div.

**Comment by gravis** [comment]
thanks I thought it was just not implemented. I'll try with the wrapping div and let you know.
(sorry for double -private- message malsup)
