### ISSUE TITLE
Help. Cant get this to work.

### ISSUE THREAD

**Issue by lavergara** [malsup/corner#9]
I cant figure out how this works. What am I doing wrong?

i added jquery.js and jquery.corners.js

added <code>
    <script>$(document).ready( function(){
      $('div.rounded').corner('5px');
    });
    </script>
</code>

have the following in my body tag

an outside div with id="wrap"  and class="rounded"

and four divs inside the wrap div as seen below:
div class="features rounded">Feature: One </div <br/>
div class="features rounded">Feature: Two </div <br/> 
div class="features rounded">Feature: Three</div <br/> 
div class="features rounded">Feature: Four</div <br/>

**Comment by malsup** [comment]
Please use the google group for support requests.  And it's always best to provide a link to the page that isn't working.  Thanks.
